//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemAPI2.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Dijak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dijak()
        {
            this.DijakPodročje = new HashSet<DijakPodročje>();
        }
    
        public int DijID { get; set; }
        public string DijIme { get; set; }
        public string DijPriimek { get; set; }
        [JsonIgnore]
        public string DijRazred { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> DijDatumRojstva { get; set; }
        [JsonIgnore]
        public byte[] DijaSlika { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> DijIDNadDatum { get; set; }
        [JsonIgnore]
        public string DijIDNadUstanova { get; set; }
        [JsonIgnore]
        public Nullable<System.DateTime> DijIDNadPotrditev { get; set; }
        [JsonIgnore]
        public string DijMati { get; set; }
        [JsonIgnore]
        public string DijOče { get; set; }
        [JsonIgnore]
        public Nullable<System.Guid> UserID { get; set; }
        [JsonIgnore]
        public virtual Razredniki Razredniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DijakPodročje> DijakPodročje { get; set; }
    }
}
