//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DijakPoPodročjih
    {
        public int DijID { get; set; }
        public string DijIme { get; set; }
        public string DijPriimek { get; set; }
        public string DijRazred { get; set; }
        public Nullable<System.DateTime> DijDatumRojstva { get; set; }
        public byte[] DijaSlika { get; set; }
        public Nullable<System.DateTime> DijIDNadDatum { get; set; }
        public string DijIDNadUstanova { get; set; }
        public Nullable<System.DateTime> DijIDNadPotrditev { get; set; }
        public string DijMati { get; set; }
        public string DijOče { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public int PodID { get; set; }
        public string PodIme { get; set; }
        public string DijPodTest { get; set; }
    }
}
