//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzvdebaPoDijakih
    {
        public int IzvID { get; set; }
        public Nullable<System.DateTime> IzvDatum { get; set; }
        public Nullable<int> IzvMesec { get; set; }
        public Nullable<int> IzvLeto { get; set; }
        public string IzvOpis { get; set; }
        public string IzvCilji { get; set; }
        public int DijID { get; set; }
        public string DijIme { get; set; }
        public string DijPriimek { get; set; }
        public string DijRazred { get; set; }
        public string PodIme { get; set; }
        public Nullable<int> IzvUre { get; set; }
    }
}
