//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPoMentorjih
    {
        public int PlaId { get; set; }
        public string PlaOpis { get; set; }
        public Nullable<int> PlaŠtDijakov { get; set; }
        public string PlaCilji { get; set; }
        public string PlaTrajanje { get; set; }
        public int MenId { get; set; }
        public string MenIme { get; set; }
        public string MenPriimek { get; set; }
        public byte[] MenSlika { get; set; }
        public string MenVloga { get; set; }
        public string MenNaziv { get; set; }
        public string MenUstanova { get; set; }
        public string PodIme { get; set; }
    }
}
