//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPoDijakih
    {
        public int PlaId { get; set; }
        public string PlaCilji { get; set; }
        public string PlaOpis { get; set; }
        public Nullable<int> PlaPodročje { get; set; }
        public Nullable<int> PlaŠtDijakov { get; set; }
        public string PlaTrajanje { get; set; }
        public int DijID { get; set; }
        public string DijIme { get; set; }
        public string DijPriimek { get; set; }
        public string DijRazred { get; set; }
        public string PodIme { get; set; }
    }
}
